apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrafty-app
  namespace: scrafty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrafty-app
  template:
    metadata:
      labels:
        app: scrafty-app
    spec:
      containers:
        - name: nextjs-container
          image: ghcr.io/asallh/scrafty:multi_arch
          ports:
            - containerPort: 3000