apiVersion: v1
kind: Service
metadata:
  name: scrafty-app-service
  namespace: scrafty
spec:
  selector:
    app: scrafty-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer